export default {
  id: "animaux",
  nom: "Animaux",
  vignette: "🐶",
  rendu: "emoji",
  decor: "douceur",
  couleurs: { fond: "#3a2c1e", fondClair: "#6e5539", accent: "#ffd6a5" },
  items: [
    { mot: "CHAT", affichage: "chat", visuel: "🐱" },
    { mot: "CHIEN", affichage: "chien", visuel: "🐶" },
    { mot: "OURS", affichage: "ours", visuel: "🐻" },
    { mot: "LOUP", affichage: "loup", visuel: "🐺" },
    { mot: "RENARD", affichage: "renard", visuel: "🦊" },
    { mot: "SOURIS", affichage: "souris", visuel: "🐭" },
    { mot: "LAPIN", affichage: "lapin", visuel: "🐰" },
    { mot: "CHEVAL", affichage: "cheval", visuel: "🐴" },
    { mot: "OISEAU", affichage: "oiseau", visuel: "🐦" },
    { mot: "POISSON", affichage: "poisson", visuel: "🐟" },
    { mot: "HAMSTER", affichage: "hamster", visuel: "🐹" },
    { mot: "TORTUE", affichage: "tortue", visuel: "🐢" },
    { mot: "HIBOU", affichage: "hibou", visuel: "🦉" },
    { mot: "HERISSON", affichage: "hérisson", visuel: "🦔" },
    { mot: "ECUREUIL", affichage: "écureuil", visuel: "🐿️" },
    { mot: "PAPILLON", affichage: "papillon", visuel: "🦋" },
    { mot: "GRENOUILLE", affichage: "grenouille", visuel: "🐸" },
    { mot: "PERROQUET", affichage: "perroquet", visuel: "🦜" },
  ],
  collecte: {
    objet: { visuel: "🦴", nom: "os", pluriel: "os" },
    receptacle: { visuel: "🐶", nom: "le chien",
      destination: "au chien", },
  },
};
