export default {
  id: "dinosaures",
  nom: "Dinosaures",
  vignette: "🦖",
  rendu: "emoji",
  decor: "feuilles",
  couleurs: { fond: "#1f3d1f", fondClair: "#3d6b35", accent: "#f4a261" },
  items: [
    { mot: "OS", affichage: "os", visuel: "🦴" },
    { mot: "OEUF", affichage: "œuf", visuel: "🥚" },
    { mot: "DINO", affichage: "dino", visuel: "🦖" },
    { mot: "ARBRE", affichage: "arbre", visuel: "🌳" },
    { mot: "TRACE", affichage: "trace", visuel: "🐾" },
    { mot: "VOLCAN", affichage: "volcan", visuel: "🌋" },
    { mot: "ROCHER", affichage: "rocher", visuel: "🪨" },
    { mot: "FEUILLE", affichage: "feuille", visuel: "🍃" },
    { mot: "AIGLE", affichage: "aigle", visuel: "🦅" },
    { mot: "FOUGERE", affichage: "fougère", visuel: "🌿" },
    { mot: "METEORE", affichage: "météore", visuel: "☄️" },
    { mot: "CRANE", affichage: "crâne", visuel: "💀" },
    { mot: "CROCODILE", affichage: "crocodile", visuel: "🐊" },
    { mot: "PLUME", affichage: "plume", visuel: "🪶" },
    { mot: "MONTAGNE", affichage: "montagne", visuel: "⛰️" },
    { mot: "MOUCHE", affichage: "mouche", visuel: "🪰" },
  ],
  collecte: {
    objet: { visuel: "🦴", nom: "os", pluriel: "os" },
    receptacle: { visuel: "🕳️", nom: "le trou", },
  },
};
