export default {
  id: "espace",
  nom: "Espace",
  vignette: "🚀",
  rendu: "emoji",
  decor: "etoiles",
  couleurs: { fond: "#0b1a3a", fondClair: "#1e3a6e", accent: "#ffd166" },
  items: [
    { mot: "LUNE", affichage: "lune", visuel: "🌙" },
    { mot: "MARS", affichage: "Mars", visuel: "illustrations/mars.svg" },
    { mot: "OVNI", affichage: "ovni", visuel: "🛸" },
    { mot: "TERRE", affichage: "Terre", visuel: "🌍" },
    { mot: "FUSEE", affichage: "fusée", visuel: "🚀" },
    { mot: "ALIEN", affichage: "alien", visuel: "👽" },
    { mot: "ROBOT", affichage: "robot", visuel: "🤖" },
    { mot: "ETOILE", affichage: "étoile", visuel: "⭐" },
    { mot: "SOLEIL", affichage: "soleil", visuel: "☀️" },
    { mot: "COMETE", affichage: "comète", visuel: "☄️" },
    { mot: "ROCHER", affichage: "rocher", visuel: "🪨" },
    { mot: "PLANETE", affichage: "planète", visuel: "🪐" },
    { mot: "DRAPEAU", affichage: "drapeau", visuel: "🚩" },
    { mot: "SATELLITE", affichage: "satellite", visuel: "🛰️" },
    { mot: "TELESCOPE", affichage: "télescope", visuel: "🔭" },
    { mot: "ASTRONAUTE", affichage: "astronaute", visuel: "🧑‍🚀" },
  ],
  collecte: {
    objet: { visuel: "⭐", nom: "étoile", pluriel: "étoiles" },
    receptacle: { visuel: "🌙", nom: "la lune", },
  },
};
