export default {
  id: "ferme",
  nom: "Ferme",
  vignette: "🐮",
  rendu: "emoji",
  decor: "prairie",
  couleurs: { fond: "#3d5a24", fondClair: "#527a26", accent: "#ffe066" },
  items: [
    { mot: "COQ", affichage: "coq", visuel: "🐓" },
    { mot: "CYGNE", affichage: "cygne", visuel: "🦢" },
    { mot: "VACHE", affichage: "vache", visuel: "🐮" },
    { mot: "POULE", affichage: "poule", visuel: "🐔" },
    { mot: "LAPIN", affichage: "lapin", visuel: "🐰" },
    { mot: "CHEVAL", affichage: "cheval", visuel: "🐴" },
    { mot: "MOUTON", affichage: "mouton", visuel: "🐑" },
    { mot: "COCHON", affichage: "cochon", visuel: "🐷" },
    { mot: "CANARD", affichage: "canard", visuel: "🦆" },
    { mot: "CHEVRE", affichage: "chèvre", visuel: "🐐" },
    { mot: "TRACTEUR", affichage: "tracteur", visuel: "🚜" },
    { mot: "CAROTTE", affichage: "carotte", visuel: "🥕" },
    { mot: "CITROUILLE", affichage: "citrouille", visuel: "🎃" },
    { mot: "BLE", affichage: "blé", visuel: "🌾" },
    { mot: "POMME", affichage: "pomme", visuel: "🍎" },
    { mot: "ABEILLE", affichage: "abeille", visuel: "🐝" },
    { mot: "FERMIER", affichage: "fermier", visuel: "🧑‍🌾" },
  ],
  collecte: {
    objet: { visuel: "🥕", nom: "carotte", pluriel: "carottes" },
    receptacle: { visuel: "🧺", nom: "le panier", },
  },
};
