export default {
  id: "fetes",
  nom: "Fêtes",
  vignette: "🎂",
  rendu: "emoji",
  decor: "etincelles",
  couleurs: { fond: "#4a1f2e", fondClair: "#8c3a56", accent: "#ffd6e0" },
  items: [
    { mot: "SAPIN", affichage: "sapin", visuel: "🎄" },
    { mot: "FEE", affichage: "fée", visuel: "🧚" },
    { mot: "GATEAU", affichage: "gâteau", visuel: "🎂" },
    { mot: "BOUGIE", affichage: "bougie", visuel: "🕯️" },
    { mot: "BALLON", affichage: "ballon", visuel: "🎈" },
    { mot: "CADEAU", affichage: "cadeau", visuel: "🎁" },
    { mot: "CONFETTI", affichage: "confetti", visuel: "🎊" },
    { mot: "COURONNE", affichage: "couronne", visuel: "👑" },
    { mot: "NOEUD", affichage: "nœud", visuel: "🎀" },
    { mot: "PINATA", affichage: "piñata", visuel: "🪅" },
    { mot: "MASQUE", affichage: "masque", visuel: "🎭" },
    { mot: "BONBON", affichage: "bonbon", visuel: "🍬" },
    { mot: "CHOCOLAT", affichage: "chocolat", visuel: "🍫" },
    { mot: "CITROUILLE", affichage: "citrouille", visuel: "🎃" },
    { mot: "ETOILE", affichage: "étoile", visuel: "⭐" },
    { mot: "CLOCHE", affichage: "cloche", visuel: "🔔" },
    { mot: "TROMPETTE", affichage: "trompette", visuel: "🎺" },
    { mot: "FETE", affichage: "fête", visuel: "🎉" },
    { mot: "FEUARTIFICE", affichage: "feu d'artifice", visuel: "🎆" },
  ],
  collecte: {
    objet: { visuel: "🎈", nom: "ballon", pluriel: "ballons" },
    receptacle: { visuel: "🎁", nom: "le cadeau", },
  },
};
