export default {
  id: "fruits",
  nom: "Fruits et légumes",
  vignette: "🍎",
  rendu: "emoji",
  decor: "prairie",
  couleurs: { fond: "#5c2018", fondClair: "#a8452c", accent: "#ffd166" },
  items: [
    { mot: "KIWI", affichage: "kiwi", visuel: "🥝" },
    { mot: "MAIS", affichage: "maïs", visuel: "🌽" },
    { mot: "POMME", affichage: "pomme", visuel: "🍎" },
    { mot: "POIRE", affichage: "poire", visuel: "🍐" },
    { mot: "FRAISE", affichage: "fraise", visuel: "🍓" },
    { mot: "BANANE", affichage: "banane", visuel: "🍌" },
    { mot: "CERISE", affichage: "cerises", visuel: "🍒" },
    { mot: "ORANGE", affichage: "orange", visuel: "🍊" },
    { mot: "CAROTTE", affichage: "carotte", visuel: "🥕" },
    { mot: "TOMATE", affichage: "tomate", visuel: "🍅" },
    { mot: "CITRON", affichage: "citron", visuel: "🍋" },
    { mot: "RAISIN", affichage: "raisin", visuel: "🍇" },
    { mot: "PECHE", affichage: "pêche", visuel: "🍑" },
    { mot: "MELON", affichage: "melon", visuel: "🍈" },
    { mot: "ANANAS", affichage: "ananas", visuel: "🍍" },
    { mot: "BROCOLI", affichage: "brocoli", visuel: "🥦" },
    { mot: "CHAMPIGNON", affichage: "champignon", visuel: "🍄" },
    { mot: "AUBERGINE", affichage: "aubergine", visuel: "🍆" },
    { mot: "NOISETTE", affichage: "noisette", visuel: "🌰" },
    { mot: "AIL", affichage: "ail", visuel: "🧄" },
  ],
  collecte: {
    objet: { visuel: "🍓", nom: "fraise", pluriel: "fraises" },
    receptacle: { visuel: "🧺", nom: "le panier", },
  },
};
