export default {
  id: "jungle",
  nom: "Jungle",
  vignette: "🦁",
  rendu: "emoji",
  decor: "feuilles",
  couleurs: { fond: "#123d2b", fondClair: "#1f7a52", accent: "#ffcf5c" },
  items: [
    { mot: "LION", affichage: "lion", visuel: "🦁" },
    { mot: "TIGRE", affichage: "tigre", visuel: "🐯" },
    { mot: "SINGE", affichage: "singe", visuel: "🐒" },
    { mot: "SERPENT", affichage: "serpent", visuel: "🐍" },
    { mot: "PERROQUET", affichage: "perroquet", visuel: "🦜" },
    { mot: "ELEPHANT", affichage: "éléphant", visuel: "🐘" },
    { mot: "GIRAFE", affichage: "girafe", visuel: "🦒" },
    { mot: "ZEBRE", affichage: "zèbre", visuel: "🦓" },
    { mot: "PANDA", affichage: "panda", visuel: "🐼" },
    { mot: "GORILLE", affichage: "gorille", visuel: "🦍" },
    { mot: "CROCODILE", affichage: "crocodile", visuel: "🐊" },
    { mot: "BANANE", affichage: "banane", visuel: "🍌" },
    { mot: "PAPILLON", affichage: "papillon", visuel: "🦋" },
    { mot: "HIBOU", affichage: "hibou", visuel: "🦉" },
    { mot: "FLEUR", affichage: "fleur", visuel: "🌺" },
    { mot: "GOUTTE", affichage: "goutte", visuel: "💦" },
    { mot: "GRENOUILLE", affichage: "grenouille", visuel: "🐸" },
    { mot: "PAON", affichage: "paon", visuel: "🦚" },
    { mot: "MIEL", affichage: "miel", visuel: "🍯" },
  ],
  collecte: {
    objet: { visuel: "🍌", nom: "banane", pluriel: "bananes" },
    receptacle: { visuel: "🧺", nom: "le panier", },
  },
};
