export default {
  id: "maison",
  nom: "Maison",
  vignette: "🏠",
  rendu: "emoji",
  decor: "douceur",
  couleurs: { fond: "#3a2a1e", fondClair: "#6b5138", accent: "#ffd6a5" },
  items: [
    { mot: "LIT", affichage: "lit", visuel: "🛏️" },
    { mot: "CLE", affichage: "clé", visuel: "🔑" },
    { mot: "PORTE", affichage: "porte", visuel: "🚪" },
    { mot: "LAMPE", affichage: "lampe", visuel: "💡" },
    { mot: "CHAISE", affichage: "chaise", visuel: "🪑" },
    { mot: "FENETRE", affichage: "fenêtre", visuel: "🪟" },
    { mot: "MAISON", affichage: "maison", visuel: "🏠" },
    { mot: "HORLOGE", affichage: "horloge", visuel: "🕰️" },
    { mot: "DOUCHE", affichage: "douche", visuel: "🚿" },
    { mot: "ECHELLE", affichage: "échelle", visuel: "🪜" },
    { mot: "TELEPHONE", affichage: "téléphone", visuel: "☎️" },
    { mot: "TELE", affichage: "télé", visuel: "📺" },
    { mot: "MIROIR", affichage: "miroir", visuel: "🪞" },
    { mot: "BALAI", affichage: "balai", visuel: "🧹" },
    { mot: "BOUGIE", affichage: "bougie", visuel: "🕯️" },
    { mot: "PELOTE", affichage: "pelote", visuel: "🧶" },
  ],
  collecte: {
    objet: { visuel: "🔑", nom: "clé", pluriel: "clés" },
    receptacle: { visuel: "🚪", nom: "la porte", },
  },
};
