export default {
  id: "meteo",
  nom: "Météo",
  vignette: "🌦️",
  rendu: "emoji",
  decor: "pluie",
  couleurs: { fond: "#1f3a52", fondClair: "#3f6f96", accent: "#ffe8a3" },
  items: [
    { mot: "VENT", affichage: "vent", visuel: "🌬️" },
    { mot: "PLUIE", affichage: "pluie", visuel: "🌧️" },
    { mot: "NEIGE", affichage: "neige", visuel: "❄️" },
    { mot: "ORAGE", affichage: "orage", visuel: "⛈️" },
    { mot: "SOLEIL", affichage: "soleil", visuel: "☀️" },
    { mot: "NUAGE", affichage: "nuage", visuel: "☁️" },
    { mot: "ECLAIR", affichage: "éclair", visuel: "⚡" },
    { mot: "BRUME", affichage: "brume", visuel: "🌫️" },
    { mot: "TEMPETE", affichage: "tempête", visuel: "🌪️" },
    { mot: "ARCENCIEL", affichage: "arc-en-ciel", visuel: "🌈" },
    { mot: "PARAPLUIE", affichage: "parapluie", visuel: "☂️" },
    { mot: "AVERSE", affichage: "averse", visuel: "🌦️" },
    { mot: "GLACON", affichage: "glaçon", visuel: "🧊" },
    { mot: "GOUTTE", affichage: "goutte", visuel: "💧" },
    { mot: "LUNE", affichage: "lune", visuel: "🌙" },
    { mot: "ETOILE", affichage: "étoile", visuel: "⭐" },
    { mot: "BONHOMME", affichage: "bonhomme", visuel: "⛄" },
    { mot: "THERMOMETRE", affichage: "thermomètre", visuel: "🌡️" },
  ],
  collecte: {
    objet: { visuel: "💧", nom: "goutte", pluriel: "gouttes" },
    receptacle: { visuel: "☂️", nom: "le parapluie", },
  },
};
