export default {
  id: "musique",
  nom: "Musique",
  vignette: "🎵",
  rendu: "emoji",
  decor: "ondes",
  couleurs: { fond: "#2d1b46", fondClair: "#5b3a86", accent: "#ffc6ff" },
  items: [
    { mot: "NOTE", affichage: "note", visuel: "🎵" },
    { mot: "COR", affichage: "cor", visuel: "📯" },
    { mot: "PIANO", affichage: "piano", visuel: "🎹" },
    { mot: "BANJO", affichage: "banjo", visuel: "🪕" },
    { mot: "GUITARE", affichage: "guitare", visuel: "🎸" },
    { mot: "TAMBOUR", affichage: "tambour", visuel: "🥁" },
    { mot: "TROMPETTE", affichage: "trompette", visuel: "🎺" },
    { mot: "VIOLON", affichage: "violon", visuel: "🎻" },
    { mot: "MICRO", affichage: "micro", visuel: "🎤" },
    { mot: "CASQUE", affichage: "casque", visuel: "🎧" },
    { mot: "SAXOPHONE", affichage: "saxophone", visuel: "🎷" },
    { mot: "ACCORDEON", affichage: "accordéon", visuel: "🪗" },
    { mot: "CLOCHE", affichage: "cloche", visuel: "🔔" },
    { mot: "RADIO", affichage: "radio", visuel: "📻" },
    { mot: "DISQUE", affichage: "disque", visuel: "💿" },
    { mot: "PARTITION", affichage: "partition", visuel: "🎼" },
  ],
  collecte: {
    objet: { visuel: "🎵", nom: "note", pluriel: "notes" },
    receptacle: { visuel: "🎹", nom: "le piano", },
  },
};
