export default {
  id: "nature",
  nom: "Nature",
  vignette: "🌳",
  rendu: "emoji",
  decor: "prairie",
  couleurs: { fond: "#1e3d2f", fondClair: "#3f7a5c", accent: "#c7f9cc" },
  items: [
    { mot: "EAU", affichage: "eau", visuel: "💧" },
    { mot: "FEU", affichage: "feu", visuel: "🔥" },
    { mot: "ARBRE", affichage: "arbre", visuel: "🌳" },
    { mot: "FLEUR", affichage: "fleur", visuel: "🌷" },
    { mot: "PLANTE", affichage: "plante", visuel: "🌱" },
    { mot: "NEIGE", affichage: "neige", visuel: "❄️" },
    { mot: "NUAGE", affichage: "nuage", visuel: "☁️" },
    { mot: "SOLEIL", affichage: "soleil", visuel: "☀️" },
    { mot: "MONTAGNE", affichage: "montagne", visuel: "⛰️" },
    { mot: "FORET", affichage: "forêt", visuel: "🌲" },
    { mot: "CACTUS", affichage: "cactus", visuel: "🌵" },
    { mot: "CHAMPIGNON", affichage: "champignon", visuel: "🍄" },
    { mot: "PAPILLON", affichage: "papillon", visuel: "🦋" },
    { mot: "COCCINELLE", affichage: "coccinelle", visuel: "🐞" },
    { mot: "ESCARGOT", affichage: "escargot", visuel: "🐌" },
    { mot: "ABEILLE", affichage: "abeille", visuel: "🐝" },
    { mot: "ARCENCIEL", affichage: "arc-en-ciel", visuel: "🌈" },
    { mot: "VENT", affichage: "vent", visuel: "🌬️" },
  ],
  collecte: {
    objet: { visuel: "🍀", nom: "trèfle", pluriel: "trèfles" },
    receptacle: { visuel: "🌳", nom: "l'arbre", },
  },
};
