export default {
  id: "ocean",
  nom: "Océan",
  vignette: "🐠",
  rendu: "emoji",
  decor: "bulles",
  couleurs: { fond: "#03395e", fondClair: "#0a6ba8", accent: "#7bdff2" },
  items: [
    { mot: "MER", affichage: "mer", visuel: "🌊" },
    { mot: "CRABE", affichage: "crabe", visuel: "🦀" },
    { mot: "PHOQUE", affichage: "phoque", visuel: "🦭" },
    { mot: "REQUIN", affichage: "requin", visuel: "🦈" },
    { mot: "POISSON", affichage: "poisson", visuel: "🐠" },
    { mot: "PIEUVRE", affichage: "pieuvre", visuel: "🐙" },
    { mot: "BALEINE", affichage: "baleine", visuel: "🐋" },
    { mot: "TORTUE", affichage: "tortue", visuel: "🐢" },
    { mot: "BATEAU", affichage: "bateau", visuel: "⛵" },
    { mot: "DAUPHIN", affichage: "dauphin", visuel: "🐬" },
    { mot: "CREVETTE", affichage: "crevette", visuel: "🦐" },
    { mot: "ANCRE", affichage: "ancre", visuel: "⚓" },
    { mot: "ILE", affichage: "île", visuel: "🏝️" },
    { mot: "COQUILLAGE", affichage: "coquillage", visuel: "🐚" },
    { mot: "PINGOUIN", affichage: "pingouin", visuel: "🐧" },
  ],
  collecte: {
    objet: { visuel: "🐚", nom: "coquillage", pluriel: "coquillages" },
    receptacle: { visuel: "🪣", nom: "le seau", },
  },
};
