export default {
  id: "princesses",
  nom: "Princesses",
  vignette: "👑",
  rendu: "emoji",
  decor: "etincelles",
  couleurs: { fond: "#4a1942", fondClair: "#8e3b73", accent: "#ffd6ec" },
  items: [
    { mot: "ROI", affichage: "roi", visuel: "🤴" },
    { mot: "FEE", affichage: "fée", visuel: "🧚" },
    { mot: "ROBE", affichage: "robe", visuel: "👗" },
    { mot: "BAGUE", affichage: "bague", visuel: "💍" },
    { mot: "MIROIR", affichage: "miroir", visuel: "🪞" },
    { mot: "DRAGON", affichage: "dragon", visuel: "🐉" },
    { mot: "LICORNE", affichage: "licorne", visuel: "🦄" },
    { mot: "CHATEAU", affichage: "château", visuel: "🏰" },
    { mot: "COURONNE", affichage: "couronne", visuel: "👑" },
    { mot: "FLEUR", affichage: "fleur", visuel: "🌸" },
    { mot: "ETOILE", affichage: "étoile", visuel: "⭐" },
    { mot: "GATEAU", affichage: "gâteau", visuel: "🎂" },
    { mot: "CHEVAL", affichage: "cheval", visuel: "🐴" },
    { mot: "BOUGIE", affichage: "bougie", visuel: "🕯️" },
    { mot: "CLEF", affichage: "clef", visuel: "🗝️" },
    { mot: "DIAMANT", affichage: "diamant", visuel: "💎" },
    { mot: "BULLE", affichage: "bulle", visuel: "🫧" },
    { mot: "PAPILLON", affichage: "papillon", visuel: "🦋" },
  ],
  collecte: {
    objet: { visuel: "💎", nom: "diamant", pluriel: "diamants" },
    receptacle: { visuel: "👛", nom: "la bourse", },
  },
};
