export default {
  id: "robots",
  nom: "Robots",
  vignette: "🤖",
  rendu: "emoji",
  decor: "circuits",
  couleurs: { fond: "#1c2733", fondClair: "#33475e", accent: "#00d4ff" },
  items: [
    { mot: "CLE", affichage: "clé", visuel: "🔧" },
    { mot: "PILE", affichage: "pile", visuel: "🔋" },
    { mot: "ECROU", affichage: "écrou", visuel: "🔩" },
    { mot: "ECRAN", affichage: "écran", visuel: "🖥️" },
    { mot: "ROBOT", affichage: "robot", visuel: "🤖" },
    { mot: "AMPOULE", affichage: "ampoule", visuel: "💡" },
    { mot: "MARTEAU", affichage: "marteau", visuel: "🔨" },
    { mot: "FUSEE", affichage: "fusée", visuel: "🚀" },
    { mot: "AIMANT", affichage: "aimant", visuel: "🧲" },
    { mot: "ENGRENAGE", affichage: "engrenage", visuel: "⚙️" },
    { mot: "ANTENNE", affichage: "antenne", visuel: "📡" },
    { mot: "PORTABLE", affichage: "portable", visuel: "💻" },
    { mot: "SCIE", affichage: "scie", visuel: "🪚" },
    { mot: "LOUPE", affichage: "loupe", visuel: "🔍" },
    { mot: "PRISE", affichage: "prise", visuel: "🔌" },
    { mot: "TELEPHONE", affichage: "téléphone", visuel: "📱" },
  ],
  collecte: {
    objet: { visuel: "🔩", nom: "écrou", pluriel: "écrous" },
    receptacle: { visuel: "🧰", nom: "la boîte à outils", },
  },
};
