export default {
  id: "sports",
  nom: "Sports",
  vignette: "⚽",
  rendu: "emoji",
  decor: "energie",
  couleurs: { fond: "#1b2d4d", fondClair: "#2f5a8c", accent: "#ffd166" },
  items: [
    { mot: "CAGE", affichage: "cage", visuel: "🥅" },
    { mot: "SKI", affichage: "ski", visuel: "🎿" },
    { mot: "VELO", affichage: "vélo", visuel: "🚲" },
    { mot: "NAGE", affichage: "nage", visuel: "🏊" },
    { mot: "BALLON", affichage: "ballon", visuel: "⚽" },
    { mot: "TENNIS", affichage: "tennis", visuel: "🎾" },
    { mot: "BOXE", affichage: "boxe", visuel: "🥊" },
    { mot: "COURSE", affichage: "course", visuel: "🏃" },
    { mot: "MEDAILLE", affichage: "médaille", visuel: "🥇" },
    { mot: "RUGBY", affichage: "rugby", visuel: "🏉" },
    { mot: "PATINS", affichage: "patins", visuel: "⛸️" },
    { mot: "ESCALADE", affichage: "escalade", visuel: "🧗" },
    { mot: "TROPHEE", affichage: "trophée", visuel: "🏆" },
    { mot: "CHRONO", affichage: "chrono", visuel: "⏱️" },
    { mot: "SURF", affichage: "surf", visuel: "🏄" },
    { mot: "GOLF", affichage: "golf", visuel: "⛳" },
    { mot: "GYMNASTIQUE", affichage: "gymnastique", visuel: "🤸" },
  ],
  collecte: {
    objet: { visuel: "🏅", nom: "médaille", pluriel: "médailles" },
    receptacle: { visuel: "🏆", nom: "le trophée", },
  },
};
