export default {
  id: "vehicules",
  nom: "Véhicules",
  vignette: "🚗",
  rendu: "emoji",
  decor: "route",
  couleurs: { fond: "#232b3d", fondClair: "#425070", accent: "#ffb703" },
  items: [
    { mot: "BUS", affichage: "bus", visuel: "🚌" },
    { mot: "VELO", affichage: "vélo", visuel: "🚲" },
    { mot: "MOTO", affichage: "moto", visuel: "🏍️" },
    { mot: "TRAIN", affichage: "train", visuel: "🚂" },
    { mot: "AVION", affichage: "avion", visuel: "✈️" },
    { mot: "BATEAU", affichage: "bateau", visuel: "⛵" },
    { mot: "VOITURE", affichage: "voiture", visuel: "🚗" },
    { mot: "CAMION", affichage: "camion", visuel: "🚚" },
    { mot: "FUSEE", affichage: "fusée", visuel: "🚀" },
    { mot: "TRACTEUR", affichage: "tracteur", visuel: "🚜" },
    { mot: "TAXI", affichage: "taxi", visuel: "🚕" },
    { mot: "METRO", affichage: "métro", visuel: "🚇" },
    { mot: "SCOOTER", affichage: "scooter", visuel: "🛵" },
    { mot: "HELICOPTERE", affichage: "hélicoptère", visuel: "🚁" },
    { mot: "AMBULANCE", affichage: "ambulance", visuel: "🚑" },
    { mot: "POMPIER", affichage: "pompier", visuel: "🧑‍🚒" },
    { mot: "TROTTINETTE", affichage: "trottinette", visuel: "🛴" },
    { mot: "BALLON", affichage: "ballon", visuel: "🎈" },
  ],
  collecte: {
    objet: { visuel: "📦", nom: "carton", pluriel: "cartons" },
    receptacle: { visuel: "🚚", nom: "le camion", },
  },
};
